# Generated by Django 4.1.4 on 2023-01-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_id_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('pending', 'PEnding'), ('paid', 'Paid'), ('on_the_way', 'On The Way'), ('stolen', 'Stolen')], max_length=20),
        ),
    ]
