# Generated by Django 4.1.4 on 2023-01-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pending_payment_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('on_the_way', 'On The Way'), ('paid', 'Paid'), ('stolen', 'Stolen'), ('pending', 'Pending')], max_length=20),
        ),
    ]
