# Generated by Django 4.1.4 on 2023-01-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_pending_payment_url_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pending_payment_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('on_the_way', 'On The Way'), ('stolen', 'Stolen'), ('paid', 'Paid'), ('pending', 'Pending'), ('delivered', 'Delivered')], max_length=20),
        ),
    ]
