# Generated by Django 4.1.4 on 2023-01-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_pending_payment_url_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('stolen', 'Stolen'), ('paid', 'Paid'), ('pending', 'Pending'), ('on_the_way', 'On The Way')], max_length=20),
        ),
    ]
