# Generated by Django 4.1.4 on 2023-01-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('on_the_way', 'On The Way'), ('pending', 'Pending'), ('paid', 'Paid'), ('delivered', 'Delivered'), ('stolen', 'Stolen')], max_length=20),
        ),
    ]
