# Generated by Django 4.1.4 on 2023-01-04 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_review_food_alter_order_status_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('on_the_way', 'On The Way'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('stolen', 'Stolen')], max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('1', '1'), ('5', '5')], max_length=5),
        ),
    ]
