# Generated by Django 4.1.4 on 2023-01-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_cart_created_at_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='rating',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('5', '5'), ('4', '4'), ('1', '1')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='review',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('stolen', 'Stolen'), ('paid', 'Paid'), ('pending', 'Pending'), ('on_the_way', 'On The Way')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
