# Generated by Django 4.1.4 on 2023-01-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_cart_rating_cart_review_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='rating',
            field=models.CharField(blank=True, choices=[('5', '5'), ('2', '2'), ('4', '4'), ('1', '1'), ('3', '3')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('stolen', 'Stolen'), ('delivered', 'Delivered'), ('paid', 'Paid'), ('pending', 'Pending'), ('on_the_way', 'On The Way')], max_length=20),
        ),
    ]
