# Generated by Django 4.1.4 on 2023-01-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
