# Generated by Django 4.1.4 on 2023-01-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('buyer', 'buyer'), ('seller', 'seller'), ('deliver', 'deliver')], max_length=10),
        ),
    ]
