# Generated by Django 4.1.4 on 2023-01-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('buyer', 'buyer'), ('deliver', 'deliver'), ('seller', 'seller')], max_length=10),
        ),
    ]
