# Generated by Django 4.1.4 on 2023-01-03 11:10

from django.db import migrations, models
import utils.misc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=utils.misc.profile_image_path),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('seller', 'seller'), ('deliver', 'deliver'), ('buyer', 'buyer')], max_length=10),
        ),
    ]
